server:
  port: 8222
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes[0]:
        id: service-acl
        uri: lb://service-acl
        predicates: Path=/*/acl/**
      routes[1]:
        id: service-simulink
        uri: lb://service-simulink
        predicates: Path=/simulink/**
      routes[2]:
        id: service-oss
        uri: lb://service-oss
        predicates: Path=/eduoss/**
      routes[3]:
        id: service-manage
        uri: lb://service-manage
        predicates: Path=/manageservice/**
      routes[4]:
        id: service-ucenter
        uri: lb://service-ucenter
        predicates: Path=/educenter/**
      routes[5]:
        id: service-msm
        uri: lb://service-msm
        predicates: Path=/eduemsm/**